const nav = [
  {label:"Get started",items:[["overview","Overview","⌂"],["principles","Principles","◇"]]},
  {label:"Design",items:[["foundations","Foundations","◫"],["styling-hooks","Styling hooks","{}"],["components","Components","▦"],["patterns","Patterns","⌘"]]},
  {label:"Build together",items:[["figma","Figma mapping","F"],["agent","Agent","A"],["qa","QA & governance","✓"]]}
];

const summaries={
  overview:"System status, architecture, and the quickest paths into AH Design System.",principles:"The source hierarchy and operating rules that keep the system coherent.",foundations:"Color, typography, spacing, shape, and responsive foundations from the audited Core DS.","styling-hooks":"Stable semantic interfaces for applying design decisions without binding to raw values.",components:"Core reusable UI families and their audited component identities.",patterns:"Business-aware structures and reusable page compositions.",figma:"Map documentation concepts to canonical Figma files, nodes, and libraries.",agent:"Understand how Chat, GitHub, and Figma work together in the Design Control Agent.",qa:"Evidence-driven gates for fidelity, accessibility, responsive behavior, and scope control."
};

const datasets={};
const files={foundations:"registry/core-ds-foundations.json",components:"registry/core-ds-components.json",patterns:"registry/domain-patterns.json",templates:"registry/templates.json",sources:"registry/figma-sources.json",coverage:"registry/core-ds-coverage.json",flows:"registry/state-flows.json",runtime:"agent/runtime.json",qa:"agent/gates/quality-gates.json"};

async function loadData(){
  await Promise.all(Object.entries(files).map(async([key,path])=>{try{datasets[key]=await fetch(`./data/${path}`).then(r=>r.json())}catch{datasets[key]={}}}));
}

function icon(name){return `<span class="icon-tile" aria-hidden="true">${name}</span>`}
function pageHeader(section,title,desc){return `<div class="breadcrumbs"><a href="#/overview">AH Design System</a><span>/</span><span>${section}</span></div><div class="eyebrow">${section}</div><h1>${title}</h1><p class="lede">${desc}</p>`}
function footer(){return `<div class="footer-note">Source: kreecrypto/DS-AH · Repository baseline 2026-09-18 · Website generated from audited registry data.</div>`}
function countDeep(value,matcher){let n=0;const walk=v=>{if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==="object"){if(matcher(v))n++;Object.values(v).forEach(walk)}};walk(value);return n}
function objectRows(obj,prefix=""){const rows=[];const walk=(v,path)=>{if(rows.length>80)return;if(Array.isArray(v)){v.slice(0,30).forEach((x,i)=>walk(x,`${path}[${i}]`))}else if(v&&typeof v==="object"){const title=v.name||v.id||v.family||v.title||v.canonicalName;if(title)rows.push({name:String(title),path,status:v.status||v.reviewStatus||v.ownership||v.layer||"Audited"});else Object.entries(v).forEach(([k,x])=>walk(x,path?`${path}.${k}`:k))}};walk(obj,prefix);return rows}
function sourceArray(obj){if(Array.isArray(obj))return obj;for(const v of Object.values(obj||{}))if(Array.isArray(v)&&v.length)return v;return objectRows(obj)}

const pages={
overview(){const componentCount=countDeep(datasets.components,x=>!!(x.name||x.family)&&Object.keys(x).length>2);const patternCount=countDeep(datasets.patterns,x=>!!(x.name||x.id)&&Object.keys(x).length>2);return `${pageHeader("Get started","Build consistent AdvisorHub experiences","A shared system for designers, developers, and agents—grounded in audited Figma sources and governed through GitHub.")}<div class="overview-grid"><section class="panel panel-accent"><div class="eyebrow" style="color:#93c5fd">System at a glance</div><h2>One source. Clear decisions.</h2><p>Foundations and component identities come from the Core Design System. Approved domain patterns add business meaning. Screens compose both without inventing a parallel system.</p><div class="metric-row"><div class="metric"><strong>${componentCount||57}</strong><span>Core entries</span></div><div class="metric"><strong>${patternCount||16}</strong><span>Domain patterns</span></div><div class="metric"><strong>10</strong><span>QA gates</span></div></div></section><aside class="panel"><h2>Start here</h2><ul class="quick-list"><li><a href="#/foundations">Explore foundations <span>→</span></a></li><li><a href="#/components">Browse components <span>→</span></a></li><li><a href="#/figma">Find Figma sources <span>→</span></a></li><li><a href="#/qa">Run a QA gate <span>→</span></a></li></ul></aside></div><section class="section"><h2>System architecture</h2><p class="lede" style="font-size:16px;margin-bottom:20px">Dependency direction keeps local decisions traceable and prevents screen-level exceptions from becoming accidental standards.</p><div class="card-grid">${[["Foundation","Tokens","Color, type, spacing, shape, and responsive primitives."],["Core","Components","Cross-domain controls such as Button, Input, Menu, and Badge."],["Domain","Patterns","Business-aware structures for AdvisorHub workflows."],["Template","Layouts","Repeatable List, Detail, Form, Dashboard, and Search compositions."],["Screen","Products","Feature-specific assemblies with verified content and behavior."],["Agent","Governance","Reference locking, permission control, QA, and evidence."]].map(([i,t,d])=>`<a class="doc-card" href="#/${t.toLowerCase()}">${icon(i[0])}<h3>${i}</h3><p>${d}</p><span class="meta">View guidance →</span></a>`).join("")}</div></section>${footer()}`},
principles(){return `${pageHeader("Get started","Principles","The contract for resolving sources, reusing assets, and making controlled changes across AdvisorHub products.")}<div class="callout"><strong>Inspect → resolve → reuse → verify</strong><p>Search the approved Core library before creating. Treat raw screen values as evidence, not canonical foundations.</p></div><section class="section"><h2>Source hierarchy</h2><div class="card-grid">${[["01","Core Design System","Canonical foundations and cross-domain components."],["02","Current Master","Approved product behavior and visual evidence."],["03","Domain Pattern","Reusable business-aware structure."],["04","Feature Screen","Composition specific to one use case."],["05","Draft / archive","Research only—never an implementation source."]].map(([n,t,d])=>`<div class="doc-card">${icon(n)}<h3>${t}</h3><p>${d}</p></div>`).join("")}</div></section>${footer()}`},
foundations(){const colors=[['#0b2e59','Brand / Navy'],['#1769e0','Action / Blue'],['#172033','Text / Primary'],['#5d6a7e','Text / Secondary'],['#d9e1eb','Stroke / Default'],['#f6f8fb','Surface / Subtle'],['#18864b','Feedback / Success'],['#aa6400','Feedback / Warning'],['#c53030','Feedback / Error'],['#ffffff','Surface / Base']];return `${pageHeader("Design","Foundations","The visual decisions beneath every component: semantic color roles, typography, spacing, shape, and responsive behavior.")}<div class="callout"><strong>Audited source first</strong><p>These pages explain roles. Canonical values remain governed by the bound variables registered in the Core DS evidence.</p></div><section class="section"><h2>Semantic color roles</h2><div class="swatch-grid">${colors.map(([c,n])=>`<div class="swatch"><div class="swatch-color" style="background:${c}"></div><div class="swatch-info"><strong>${n}</strong><span>${c}</span></div></div>`).join("")}</div></section><section class="section"><h2>Foundation families</h2><div class="card-grid">${[["Aa","Typography","Roles, scale, weight, and readable line height."],["8pt","Spacing","Consistent layout rhythm and component density."],["◜","Shape","Radius and container geometry."],["↔","Responsive","Desktop, Tablet, and Mobile behavior."],["◐","Elevation","Layering and focus without decorative noise."],["✓","Feedback","Success, warning, error, and information roles."]].map(([i,t,d])=>`<div class="doc-card">${icon(i)}<h3>${t}</h3><p>${d}</p></div>`).join("")}</div></section>${footer()}`},
"styling-hooks"(){return `${pageHeader("Design","Styling hooks","Semantic CSS custom properties mirror system roles, so themes can evolve without rewriting component anatomy.")}<section class="section"><h2>Core interface</h2><pre class="code-block"><code>:root {
  --ah-color-bg-brand: #0b2e59;
  --ah-color-action-primary: #1769e0;
  --ah-color-text-primary: #172033;
  --ah-color-stroke-default: #d9e1eb;
  --ah-space-component-inline: 1rem;
  --ah-radius-control: .25rem;
}</code></pre></section><div class="callout"><strong>Foundation → hook → component</strong><p>Raw values remain implementation detail. Components consume semantic roles; screens consume components.</p></div>${footer()}`},
components(){let rows=sourceArray(datasets.components).slice(0,50);if(!rows.length)rows=['Button','Icon Button','Input','Menu','Badge','Divider','Tab / Chip','Checkbox','Radio','Breadcrumb'].map(name=>({name,status:'Audited',path:'Core'}));return `${pageHeader("Design","Components","Cross-domain primitives resolved from the audited Core Design System library.")}<div class="demo-stage"><button class="ah-button">Primary action</button><button class="ah-button secondary">Secondary</button><button class="ah-button ghost">Ghost</button><button class="ah-button" disabled>Disabled</button><input class="ah-input" aria-label="Example input" placeholder="Input example" /></div><div class="inventory-toolbar"><div class="chip-row"><span class="chip selected">All</span><span class="chip">Action</span><span class="chip">Form</span><span class="chip">Navigation</span><span class="chip">Feedback</span></div><input id="inventoryFilter" class="filter-input" placeholder="Filter components" /></div><div class="table-wrap"><table><thead><tr><th>Component</th><th>Registry path</th><th>Status</th></tr></thead><tbody id="inventoryBody">${rows.map(r=>`<tr><td><strong>${escapeHtml(r.name)}</strong></td><td>${escapeHtml(r.path||'Core DS')}</td><td><span class="tag good">${escapeHtml(String(r.status||'Audited'))}</span></td></tr>`).join("")}</tbody></table></div>${footer()}`},
patterns(){let rows=sourceArray(datasets.patterns).slice(0,24);if(!rows.length)rows=['Case status','Campaign card','Performance section','Compensation table','Live-chat flow','Memo drawer'].map(name=>({name,status:'Domain'}));return `${pageHeader("Design","Patterns","Business-aware reusable structures that compose Core components without redefining them.")}<div class="card-grid">${rows.map((r,i)=>`<div class="doc-card">${icon(String(i+1).padStart(2,'0'))}<h3>${escapeHtml(r.name||r.id||'Pattern')}</h3><p>${escapeHtml(String(r.description||r.summary||'Approved domain structure with canonical semantics and documented ownership.'))}</p><span class="meta">${escapeHtml(String(r.status||'Domain pattern'))}</span></div>`).join("")}</div>${footer()}`},
figma(){let rows=sourceArray(datasets.sources).slice(0,30);return `${pageHeader("Build together","Figma mapping","Trace documentation to approved Figma files, libraries, and audited nodes before creating or modifying work.")}<div class="callout"><strong>Core → domain → template → screen</strong><p>Visual authority and system authority are separate. Figma sources establish both without allowing one to silently replace the other.</p></div><div class="table-wrap"><table><thead><tr><th>Source</th><th>Evidence path</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${escapeHtml(r.name)}</strong></td><td>${escapeHtml(r.path||'registry/figma-sources.json')}</td><td><span class="tag">${escapeHtml(String(r.status||'Registered'))}</span></td></tr>`).join('')||'<tr><td colspan="3">Canonical Core DS: 5ZFIRJWtmEIvuq95Rhyo6I</td></tr>'}</tbody></table></div>${footer()}`},
agent(){const seq=datasets.runtime?.sequence||['ROUTE_INTENT','INSPECT_LIVE_FIGMA','LOCK_REFERENCE','EXTRACT_VISUAL_GRAMMAR','MAP_DESIGN_SYSTEM_TO_VISUAL_ROLES','EXECUTE_MUTATION','VERIFY_RESULT','COMPLETE'];return `${pageHeader("Build together","Design Control Agent","Chat makes controlled decisions, GitHub stores knowledge, and Figma remains the inspected execution workspace.")}<div class="overview-grid"><div class="panel panel-accent"><h2>Chat → GitHub → Figma</h2><p>Reference authority is locked before design decisions. Write permission is explicit. Every completion is evidence-backed.</p></div><div class="panel"><h2>Runtime</h2><p>Version <strong>${escapeHtml(datasets.runtime?.agentVersion||'2.4.0')}</strong><br />Default mode <strong>Read-only</strong><br />Build mode <strong>Reproduce when reference exists</strong></p></div></div><section class="section"><h2>Execution sequence</h2><div class="card-grid">${seq.slice(0,12).map((s,i)=>`<div class="doc-card">${icon(String(i+1).padStart(2,'0'))}<h3>${escapeHtml(s.replaceAll('_',' '))}</h3><p>Controlled stage in the production design flow.</p></div>`).join('')}</div></section>${footer()}`},
qa(){const gates=sourceArray(datasets.qa).slice(0,30);return `${pageHeader("Build together","QA & governance","Separate reference authority, visual fidelity, system compliance, and regression so a polished but incorrect result cannot pass.")}<div class="callout"><strong>No PASS without evidence</strong><p>Each applicable gate must resolve with traceable inspection, comparison, or verification output.</p></div><div class="card-grid">${(gates.length?gates:Array.from({length:10},(_,i)=>({name:`QA-${String(i+1).padStart(2,'0')}`,status:'Required'}))).map((g,i)=>`<div class="doc-card">${icon(`Q${i+1}`)}<h3>${escapeHtml(g.name||g.id||`QA-${i+1}`)}</h3><p>${escapeHtml(String(g.description||g.purpose||'Evidence-based quality gate.'))}</p><span class="meta">${escapeHtml(String(g.status||'Required'))}</span></div>`).join('')}</div>${footer()}`}
};

function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function renderNav(){document.querySelector('#primaryNav').innerHTML=nav.map(g=>`<div class="nav-group"><div class="nav-group-title">${g.label}</div>${g.items.map(([id,label,ico])=>`<a class="nav-item" data-route="${id}" href="#/${id}"><span class="nav-icon" aria-hidden="true">${ico}</span>${label}</a>`).join('')}</div>`).join('')}
function currentRoute(){return (location.hash.match(/^#\/([^?]+)/)||[])[1]||'overview'}
function render(){const route=pages[currentRoute()]?currentRoute():'overview';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===route));document.querySelector('#main').innerHTML=`<article class="page">${pages[route]()}</article>`;document.title=`${nav.flatMap(x=>x.items).find(x=>x[0]===route)?.[1]||'AH'} · AH Design System`;document.querySelector('#main').focus({preventScroll:true});bindPage();document.querySelector('#sidebar').classList.remove('open')}
function bindPage(){const input=document.querySelector('#inventoryFilter');if(input)input.addEventListener('input',()=>{const q=input.value.toLowerCase();document.querySelectorAll('#inventoryBody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))})}
function searchIndex(){return nav.flatMap(g=>g.items.map(([id,label])=>({id,label,group:g.label,text:`${label} ${summaries[id]}`})))}
function showSearch(){const d=document.querySelector('#searchDialog');d.showModal();const i=document.querySelector('#searchInput');i.value='';renderSearch('');setTimeout(()=>i.focus(),20)}
function renderSearch(q){const matches=searchIndex().filter(x=>x.text.toLowerCase().includes(q.toLowerCase()));document.querySelector('#searchResults').innerHTML=matches.map(x=>`<a class="search-result" href="#/${x.id}" data-search-result><strong>${x.label}</strong><span>${x.group} · ${summaries[x.id]}</span></a>`).join('')||'<div class="empty">No results. Try a component family or foundation.</div>';document.querySelectorAll('[data-search-result]').forEach(a=>a.addEventListener('click',()=>document.querySelector('#searchDialog').close()))}

renderNav();await loadData();render();
window.addEventListener('hashchange',render);
document.querySelector('#searchTrigger').addEventListener('click',showSearch);
document.querySelector('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));
document.querySelector('#mobileMenu').addEventListener('click',e=>{const s=document.querySelector('#sidebar');s.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(s.classList.contains('open')))});
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showSearch()}});
