import {createStructure, escapeHTML as e, href} from './structure.js';
import {sidebar, renderPage} from './structure-view.js';
const main=document.querySelector('#main'),nav=document.querySelector('#primaryNav');
const search=document.querySelector('#searchDialog'),input=document.querySelector('#searchInput'),results=document.querySelector('#searchResults');
const expanded=new Set();let structure,currentID='';
const notify=text=>{document.querySelector('#announcement').textContent=text;};
document.querySelector('.skip-link').addEventListener('click',event=>{event.preventDefault();main.focus();});
async function getJSON(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(path,{signal:controller.signal});if(!response.ok)throw Error('Request failed');return await response.json();}finally{clearTimeout(timer);}}
function renderNav(){nav.innerHTML=sidebar(structure.navigation,currentID,expanded);}
function sectionScroll(id){const target=document.getElementById(id);if(target){target.tabIndex=-1;target.focus({preventScroll:true});target.scrollIntoView({block:'start'});}}
function closeMobile(){document.body.classList.remove('nav-open');document.querySelector('#mobileMenu').setAttribute('aria-expanded','false');}
function render(){const route=structure.resolve(location.hash);if(route.id!==currentID){currentID=route.id;const page=structure.pages.get(route.id);for(const ancestor of page?.ancestors || [])expanded.add(ancestor.id);if(page?.children.length)expanded.add(page.id);main.innerHTML=renderPage(route.id,structure);document.title=`${page?.label || (route.id==='overview'?'Home':'Page not found')} · AH Design System`;main.scrollTop=0;main.focus({preventScroll:true});}renderNav();if(route.section)sectionScroll(route.section);closeMobile();}
function openSearch(){closeMobile();search.showModal();input.value='';showResults();input.focus();}
function showResults(){const query=input.value.trim().toLowerCase();const all=[...structure.pages.values()].filter(p=>!p.isTab).filter(p=>`${p.ancestors.map(a=>a.label).join(' ')} ${p.label}`.toLowerCase().includes(query));const shown=all.slice(0,60);results.innerHTML=`<p class="search-count">${all.length} pages${all.length>60?' · showing first 60':''}</p>${shown.map(p=>`<a href="${href(p.id)}"><strong>${e(p.label)}</strong><small>${e(p.ancestors.map(a=>a.label).join(' / ') || 'Overview')}</small></a>`).join('') || '<p>No matching pages.</p>'}`;}
nav.addEventListener('click',event=>{const b=event.target.closest('[data-expand]');if(b){const id=b.dataset.expand;expanded.has(id)?expanded.delete(id):expanded.add(id);renderNav();nav.querySelector(`[data-expand="${CSS.escape(id)}"]`)?.focus();}});
main.addEventListener('click',async event=>{
  const section=event.target.closest('[data-section]');if(section){event.preventDefault();history.replaceState(null,'',href(currentID)+'?section='+section.dataset.section);sectionScroll(section.dataset.section);section.closest('details').open=false;}
  if(event.target.closest('[data-copy]')){try{await navigator.clipboard.writeText(location.href);notify('Page link copied.');}catch{notify('Unable to copy automatically. Copy the address from your browser.');}}
  if(event.target.closest('[data-download]')){const article=main.querySelector('article');const text=`# ${article.querySelector('h1').textContent}\n\n${Array.from(article.querySelectorAll('.page-body h2,.page-body h3,.page-body .pending span')).map(x=>x.tagName==='H2'?'## '+x.textContent:x.tagName==='H3'?'### '+x.textContent:x.textContent).join('\n\n')}\n\nContent is pending.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ah-design-system.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Markdown downloaded.');}
});
document.querySelector('#searchTrigger').addEventListener('click',openSearch);document.querySelector('#mobileSearch').addEventListener('click',openSearch);input.addEventListener('input',showResults);results.addEventListener('click',event=>{if(event.target.closest('a'))search.close();});
document.querySelector('#mobileMenu').addEventListener('click',()=>{const open=document.body.classList.toggle('nav-open');document.querySelector('#mobileMenu').setAttribute('aria-expanded',String(open));if(open)nav.querySelector('a')?.focus();});document.querySelector('#navBackdrop').addEventListener('click',closeMobile);
document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(structure)openSearch();}if(event.key==='Escape'&&document.body.classList.contains('nav-open')){closeMobile();document.querySelector('#mobileMenu').focus();}});
window.addEventListener('hashchange',()=>{if(structure)render();});
try{const [reference,captures,source]=await Promise.all([getJSON('./reference-navigation.json'),getJSON('./reference-pages.json'),getJSON('./data/component-packages.json')]);if(!Array.isArray(reference.navigation)||!Array.isArray(source.packages))throw Error('Navigation unavailable');structure=createStructure(reference,captures,source.packages);render();document.querySelectorAll('[data-search-button]').forEach(b=>b.disabled=false);}catch{main.innerHTML='<article><h1>Unable to load documentation</h1><p>Please check your connection and reload the page.</p><button type="button" id="retry">Try again</button></article>';document.querySelector('#retry').addEventListener('click',()=>location.reload());}
