import {escapeHTML as e} from './structure.js';
const figma=(p,id)=>`https://www.figma.com/design/${p.authority.fileKey}/?node-id=${id.replace(':','-')}`;
const link=(url,label)=>`<a href="${e(url)}" target="_blank" rel="noreferrer">${e(label)} ↗</a>`;
const table=(heads,rows)=>`<div class="source-table" tabindex="0" role="region" aria-label="${e(heads.join(', '))}"><table><thead><tr>${heads.map(x=>`<th scope="col">${e(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const list=items=>`<ul>${items.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`;
const badge=status=>`<span class="source-status">${e(status)}</span>`;
const note=text=>`<p class="source-note">${e(text)}</p>`;
const value=v=>typeof v==='object'?JSON.stringify(v):String(v??'—');
export const packageReferences={avatar:'94085e-avatar',badge:'78871c-badge',breadcrumb:'13cc12-breadcrumbs',button:'7733f8-button','check-box':'980561-checkbox','date-picker':'531362-datepicker',input:'8268ee-input',radio:'19c76a-radio-group',tab:'1152cf-tabs',toggle:'00c862-checkbox-toggle',tooltips:'532fc5-tooltip',navbar:'60977d-vertical-navigation'};
export function packageDirectory(packages){return `<section class="source-directory"><h2>AH component source packages</h2><p lang="th">ข้อมูลต้นฉบับจาก Figma พร้อมสถานะความพร้อมเผยแพร่แต่ละชุด</p><div class="cards columns-2">${packages.map(p=>`<a class="card" href="#${e(p.website.route)}"><div><h3>${e(p.name)}</h3>${badge(p.status)}<p>${p.components.length} component owners</p></div></a>`).join('')}</div></section>`;}
export function componentContent(p,tab='All'){
  const s=p.enrichment;
  const sections=[
    {name:'Overview',html:`${badge(p.status)}${note(p.status==='WEB_READY'?'Web readiness requirements verified.':'Source documentation is available. This package has not passed WEB_READY.')}${link(figma(p,p.authority.pageId),'Open Figma source')} · <a href="./data/components/${e(p.id)}.json" download>Download source package</a>${table(['Owner','Source identity','Variants'],p.components.map(c=>[link(figma(p,c.nodeId),c.figmaName),`<code>${e(c.componentKey)}</code>`,e(c.variantCount??1)]))}`},
    {name:'Anatomy',html:`${badge(s.anatomy.status)}${note(s.anatomy.coverage)}${s.anatomy.owners.map(o=>`<details><summary>${e(o.name)} · ${e(o.nodeId)}</summary><p>${link(figma(p,o.representativeId),'Inspected variant')}</p>${table(['Layer','Type','Parent','Size','Visible'],o.nodes.map(n=>[`${e(n.name)}<small>${e(n.id)}</small>`,e(n.type),e(n.parentId),`${e(n.width)} × ${e(n.height)}`,String(n.visible)]))}</details>`).join('')}`},
    {name:'Usage',html:`${badge(s.usage.status)}${note(s.usage.provenance)}${list(s.usage.items)}${note(s.usage.sourceDescription)}`},
    {name:'Accessibility',html:`${badge(s.accessibility.status)}${note(s.accessibility.provenance)}${list(s.accessibility.items)}${s.accessibility.evidence.map(url=>link(url,'Reference guidance')).join(' ')}${note('Browser keyboard, screen-reader, contrast and responsive tests are pending. These requirements are not a conformance result.')}`},
    {name:'Token Dependencies',html:`${badge(s.tokenDependencySubset.status)}${note(s.tokenDependencySubset.coverage)}${table(['Token','Collection','Values / status'],s.tokenDependencySubset.tokens.map(t=>[e(t.name||t.id),e(t.collection||'Unresolved'),e(t.values?value(t.values):t.status)]))}`},
    {name:'Examples',html:`${badge(s.examples.status)}${note(s.examples.provenance)}${s.examples.owners.map(o=>`<details><summary>${e(o.name)} · ${o.variants.length} source variants</summary><h3>Figma property API</h3>${table(['Property','Type','Default','Allowed values'],Object.entries(o.api).map(([key,v])=>[e(key),e(v.type),e(value(v.defaultValue)),e((v.variantOptions||[]).join(', '))]))}<h3>Exact source variants</h3>${table(['Variant','Source node','Size'],o.variants.map(v=>[e(v.name),link(figma(p,v.id),v.id),`${e(v.width)} × ${e(v.height)}`]))}<pre><code>${e(JSON.stringify({fileKey:p.authority.fileKey,componentKey:o.key,sourceNodeId:o.nodeId,defaults:Object.fromEntries(Object.entries(o.api).map(([key,v])=>[key,v.defaultValue]))},null,2))}</code></pre></details>`).join('')}`},
    {name:'Visual Baseline',html:`${badge(s.visualReference.status)}${note(s.visualReference.coverage)}${s.visualReference.artifacts.map(a=>`<figure class="source-figure"><div><img src="./${e(a.path)}" width="${e(a.width)}" height="${e(a.height)}" alt="Figma source specimen ${e(p.name)} — node ${e(a.nodeId)}" loading="lazy"></div><figcaption>${link(figma(p,a.nodeId),a.nodeId)} · Exported from Figma · visual verification pending</figcaption></figure>`).join('')}${s.visualReference.missingOwnerIds.length?note('Pending exports: '+s.visualReference.missingOwnerIds.join(', ')):''}`},
    {name:'Related Components',html:`${badge(s.relatedComponents.status)}${note(s.relatedComponents.provenance)}${s.relatedComponents.items.length?table(['Dependency','Key','Occurrences','Package'],s.relatedComponents.items.map(d=>[e(d.name),`<code>${e(d.key||'Unresolved')}</code>`,e(d.count),d.packageId?`<a href="#/components/${e(d.packageId)}">${e(d.packageId)}</a>`:'External / asset owner'])):note('No nested component instances were found in the inspected owner subtrees.')}`},
    {name:'QA',html:`${note('WEB_READY requires all seven sections to be verified, complete evidence, and passing runtime, responsive, accessibility and visual-regression checks.')}${table(['Gate','Status'],Object.entries(p.webValidation).map(([k,v])=>[e(k),badge(v.status)]))}`}
  ];
  const byTab={Usage:['Overview','Anatomy','Usage','Related Components'],Develop:['Overview','Examples'],Specifications:['Overview','Anatomy','Token Dependencies','Visual Baseline'],Accessibility:['Overview','Accessibility','QA']};
  const shown=byTab[tab]?sections.filter(s=>byTab[tab].includes(s.name)):sections;
  return {headings:shown.map(s=>({label:s.name,level:2})),body:shown.map((s,i)=>`<section id="s-${i}" class="component-section"><h2>${e(s.name)}</h2>${s.html}</section>`).join('')};
}
