import { components, foundations, hooks, patterns, navGroups } from './catalog.js';
import { escapeHtml as e, routes, figmaLink, componentRecords, textFromHtml } from './model.js';
import { examples } from './examples.js';

const link=(url,label)=>`<a href="${e(url)}" target="_blank" rel="noreferrer">${e(label)} ↗</a>`;
const list=items=>`<ul class="check-list">${items.map(x=>`<li>${e(x)}</li>`).join('')}</ul>`;
const code=text=>`<pre class="code-block"><code>${e(text)}</code></pre>`;
const note=(title,text)=>`<div class="callout"><strong>${e(title)}</strong><p>${e(text)}</p></div>`;
const table=(headers,rows)=>`<div class="table-wrap" tabindex="0" role="region" aria-label="${e(headers.join(', '))}"><table><thead><tr>${headers.map(x=>`<th scope="col">${e(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const section=(id,title,html)=>({id,title,html});
const jsonText=v=>Array.isArray(v)?v.map(x=>x===null?'Unresolved':String(x)).join(' · '):typeof v==='object'?JSON.stringify(v):String(v??'Not recorded');
const card=(id,title,text)=>`<a class="doc-card" href="#/${e(id)}"><h3>${e(title)}</h3><p>${e(text)}</p><span class="meta">Read guidance →</span></a>`;
const rootRepo='https://github.com/kreecrypto/DS-AH';
const repo=path=>`${rootRepo}/blob/feat/ah-design-system-site/${path}`;

function tokenTable(tokens) {
  return table(['Figma token / collection','CSS hook','Recorded value / mode'],tokens.map(t=>[
    `${e(t.name)}<small>${e(t.collection)}</small>`, `<code>${e(t.hook)}</code>`, Object.entries(t.values).map(([mode,value])=>`<div>${t.collection==='color'?`<i class="inline-swatch" style="background:var(${e(t.hook)})" aria-hidden="true"></i>`:''}<code>${e(value)}</code> <small>${e(mode)}</small></div>`).join('')
  ]));
}
function apiTable(api) {return table(['Property','Recorded values'],Object.entries(api||{}).map(([k,v])=>[e(k),e(jsonText(v))]));}
function recordsTable(records,file) { return table(['Source record','Variants','Registry status','Figma'],records.map(r=>[
  `${e(r.figmaName)}<small>${e(r.componentKey||'')}</small>`,e(r.variantCount??'—'),e(r.status||r.decision||'Not recorded'),link(figmaLink(file,r.nodeId||(r.nodeIds||[])[0]),r.nodeId||(r.nodeIds||[])[0]||'Source')
 ]));}
function recordDetails(records,file) {return records.map(r=>`<details class="record-details"><summary>${e(r.figmaName)} · ${e(r.variantCount??'—')} variants · ${e(r.status||r.decision||'Not recorded')}</summary><p>${link(figmaLink(file,r.nodeId||(r.nodeIds||[])[0]),'Inspect exact Figma node')}</p><h3>Exact Figma API</h3>${Object.keys(r.figmaCurrentApi||{}).length?apiTable(r.figmaCurrentApi):'<p>No variant axes recorded. Do not infer additional states.</p>'}${r.canonicalApi?`<h3>Canonical naming guidance</h3>${apiTable(r.canonicalApi)}<p class="muted">Naming guidance does not rename the live Figma component.</p>`:''}${r.notes?`<p>${e(r.notes)}</p>`:''}</details>`).join('');}

function componentDoc(id,data) {
  const [key,name,category,description]=components.find(x=>x[0]===id);
  const records=componentRecords(data,name), example=examples[key];
  return {title:name,description,group:'Components',badge:records.length?'Registry mapped':'Proposal / source missing',sections:[
    section('overview','Overview',note('Implementation example','Native HTML behavior and mapped foundation values. This is not a published component package or a pixel-verified Figma reproduction.')+`<div class="demo-stage">${example.html}</div>`),
    section('anatomy','Anatomy',list(example.anatomy)),
    section('variants','Source variants & states',records.length?recordsTable(records,data.components.sourceFileKey)+recordDetails(records,data.components.sourceFileKey):note('Missing registry record','Evaluation has no component identity or state API in the current Core registry. Confirm the owner and exact node before production use.')),
    section('usage','Usage',`<p>${e(example.usage)}</p>`),
    section('accessibility','Accessibility',`<p>${e(example.accessibility)}</p>`+note('Verification boundary','These are implementation requirements, not a WCAG conformance claim. Browser, keyboard and screen-reader checks remain required.')),
    section('code','Working markup',code(example.html)+(example.behavior?`<h3>Behavior contract</h3><p>${e(example.behavior)}</p><p>${link(repo('website/app.js'),'Read the event handlers')}</p>`:'')+`<p>Load <a href="./tokens.css" download>tokens.css</a> and <a href="./styles.css" download>styles.css</a> with these examples. Connect product actions separately.</p>`)
  ]};
}

function foundationDoc(id,data) {
  const [,title,description]=foundations.find(x=>x[0]===id), f=data.foundations;
  const base={title,description,group:'Visual language',badge:'Registry snapshot'};
  if(id==='color') return {...base,sections:[section('roles','Semantic color roles',`<p>${data.tokens.filter(x=>x.collection==='color').length} recorded roles. Preserve background, text, stroke and icon semantics.</p>`+tokenTable(data.tokens.filter(x=>x.collection==='color'))),section('use','Using color',code('.ah-button {\n  background: var(--ah-bg-interaction-primary-default);\n  color: var(--ah-text-interaction-primary-default);\n}')+list(['Do not convey status through color alone.','Keep exact source names in mappings; normalization only affects the CSS hook name.','Check contrast for each foreground/background pair, including hover and disabled states.']))]};
  if(id==='typography') return {...base,sections:[section('font','Typeface availability',note('Font asset not bundled','DB Helvethaica X is the recorded family. The site requests an installed local font; otherwise it uses system fallbacks. Supply a licensed webfont before claiming identical typography.')+`<p id="fontStatus" role="status">Checking local font availability…</p><div class="type-spec"><p lang="th">ออกแบบประสบการณ์ที่ชัดเจน</p><p>AdvisorHub typography specimen</p></div>`),section('scale','Desktop / Mobile scale',tokenTable(data.tokens.filter(x=>x.collection==='text'))),section('cautions','Recorded source debt',list(f.styles.text.anomalies.concat(f.styles.text.duplicateNames.map(x=>`${x.name}: ${x.definitions.join(' versus ')}`)))+note('No silent normalization','Keep anomalous source values visible for review; do not present them as verified readable combinations.'))]};
  if(id==='spacing-sizing') return {...base,sections:[section('scale','Spacing scale',tokenTable(data.tokens.filter(x=>x.collection==='spacing'))),section('use','Layout usage',code('.ah-container {\n  padding: var(--ah-padding-3xl);\n}\n.cluster { gap: var(--ah-gap-xl); }')+list(f.collections.spacing.debt))]};
  if(id==='borders-radius') return {...base,sections:[section('shape','Shape tokens',tokenTable(data.tokens.filter(x=>x.collection==='shape'))),section('use','Component mapping',code('.ah-button { border-radius: var(--ah-radius-button-default); }\n.ah-input { border-radius: var(--ah-radius-forms-input); }')+list(f.collections.shape.debt))]};
  if(id==='shadows') return {...base,badge:'No effect styles recorded',sections:[section('source','Available elevation evidence',note('No approved shadow presets',`${f.styles.effect.count} effect styles are recorded. This site uses borders for separation; browser-native modal backdrops are implementation behavior, not DS shadow tokens.`)+tokenTable(data.tokens.filter(x=>x.name.startsWith('bg/elevation'))))]};
  if(id==='responsive') return {...base,badge:'Policy review required',sections:[section('modes','Recorded modes',tokenTable(data.tokens.filter(x=>x.collection==='Responsive'))+`<p>${e(f.collections.Responsive.status)}. Text has Desktop and Mobile values, but the registry does not approve viewport breakpoints.</p>`),section('implementation','Website reflow policy',list(['The documentation sidebar becomes a disclosure at 900px; search remains available.','Article contents move above the article below 1180px.','Cards and paired examples stack at compact widths.','These are website-specific decisions, not new Core DS responsive tokens.'])+code('/* Explicit text mode, not an inferred DS breakpoint */\n<section data-text-mode="mobile">…</section>'))]};
  if(id==='density') return {...base,badge:'Implementation guidance',sections:[section('rules','Density decisions',list(['Preserve labels, focus outlines and touch access before reducing gaps.','Use recorded spacing roles; do not invent a Compact mode in the source registry.','Allow long labels and code identifiers to wrap.','Keep table columns readable with a named scroll region.'])),section('source','Relevant spacing roles',tokenTable(data.tokens.filter(x=>x.collection==='spacing' && /\/(md|lg|xl|2xl)$/.test(x.name))))]};
  return {...base,badge:'Requirements, not certification',sections:[section('keyboard','Keyboard and focus',list(['Every action must be reachable by keyboard.','Page changes move focus to the new heading. Section navigation preserves controls and values.','Dialogs have accessible names and Escape/close behavior.','Closed mobile navigation is removed from the focus order.'])),section('meaning','Names and state',list(['Labels persist outside fields.','Current routes use aria-current; category filters use aria-pressed.','Tabs connect labels and panels; error messages connect to their inputs.','Keep success, warning and error labels visible alongside color.'])),section('verification','Verification boundary',note('Manual checks required','No screen-reader or WCAG certification is claimed. Test actual devices, text enlargement, focus order and each supported state.'))]};
}

function stylingDoc(id,data) {
  const [,title,description]=hooks.find(x=>x[0]===id);
  const contents={
    'hook-index':[section('index','All recorded hooks',`<p>${data.tokens.length} unique generated hooks. Slash-separated Figma names become lowercase hyphenated names. The build rejects collisions.</p><label class="field">Find a token<input class="ah-input" id="tokenFilter" type="search" placeholder="Try radius, primary or padding"></label><p id="tokenCount" role="status"></p><div id="tokenTable">${tokenTable(data.tokens)}</div><p id="tokenEmpty" hidden>No matching tokens. Clear the search to see all hooks.</p>`)],
    'global-hooks':[section('install','Install the generated stylesheet',code('<link rel="stylesheet" href="./tokens.css">')+`<p><a href="./tokens.css" download>Download generated tokens.css</a>. Values are compiled from the registry, not copied from screen CSS.</p>`),section('mapping','Common global roles',tokenTable(data.tokens.filter(x=>['bg/interaction/primary/default','text/primary','stroke/field/default','radius/forms/input','padding/3xl','gap/xl'].includes(x.name))))],
    'component-hooks':[section('mapping','Consumed component roles',table(['Example','Property','Global hook'],[['Button','background','--ah-bg-interaction-primary-default'],['Input','border-radius','--ah-radius-forms-input'],['Input','border-color','--ah-stroke-field-default'],['Container','padding','--ah-padding-3xl']].map(r=>r.map(e)))),section('boundary','Customization boundary',note('No separate component-hook API','These examples consume global hooks directly. A versioned component-level hook contract has not been published; do not infer one from a CSS class.'))],
    'utility-classes':[section('utilities','Available website utilities',table(['Class','Behavior'],[['.stack','Vertical flex layout with recorded gap'],['.cluster','Wrapping horizontal flex layout with recorded gap'],['.visually-hidden','Accessible text hidden visually'],['[hidden]','Removes any element from layout and focus order']].map(r=>r.map(e)))),section('example','Example',code('<div class="cluster">\n  <button type="button" class="ah-button">Save</button>\n  <button type="button" class="ah-button secondary">Cancel</button>\n</div>')+note('Website utilities','These are documented implementation helpers, not Figma components.'))],
    themes:[section('current','Current theme',note('One approved color collection mode','The source color collection contains Mode 1 only. No alternative brand theme is exported.')),section('contract','Safe extension',list(['Keep semantic roles stable.','Require approved values and source ownership before introducing another theme.','Re-test contrast and all component states after an approved change.']))],
    'color-modes':[section('support','Mode support',table(['Collection','Recorded modes'],Object.entries(data.foundations.collections).map(([name,value])=>[e(name),e((value.modes||['Not recorded']).join(', '))]))),section('boundary','Dark mode boundary',note('Dark mode not published','Inverse tokens exist, but they do not constitute a complete dark theme. The website does not advertise a dark-mode switch.'))]
  };
  return {title,description,group:'Styling API',sections:contents[id]};
}

const patternGuides={
  'search-filter':{templates:['SearchFilter','List'],match:/filter/i,steps:['Enter a basic query','Add relevant criteria','Review active conditions','Inspect results or clear filters'],copy:'Keep active criteria beside results. Distinguish no matches from a failed request.',states:['Initial results','Active criteria','No matches with clear/reset','Loading','Failure with retry']},
  'list-detail':{templates:['List','Detail'],match:/Detail-card|result|Rows|Table/i,steps:['Scan the result list','Open the selected record','Review summary and detail','Return to the prior list context'],copy:'Preserve search and position when returning. Keep row actions separate from the record link.',states:['Populated list','Empty list','Selected record','Unavailable record','Return context']},
  'form-workflow':{templates:['CreateEditForm','OverlayDrawer'],match:/Form|attrachment/i,steps:['Read requirements','Enter and validate information','Review the entered values','Confirm the outcome'],copy:'Associate errors with fields, preserve entered values, and explain why submission is unavailable.',states:['Empty','Editing','Validation error','Submitting','Success','Recoverable failure']},
  dashboard:{templates:['Dashboard'],match:/dashboard|Summary|Gauge|graph|Perf Section/i,steps:['Set the reporting context','Read summary metrics','Inspect supporting detail','Take a relevant next action'],copy:'Keep period, unit and source explicit. Empty, loading and unavailable values must not appear as zero.',states:['Loading','Populated','No data','Partial data','Error','Expanded section']},
  'status-feedback':{templates:['List','OverlayDrawer'],match:/badge-status|attrachment|Table|result/i,steps:['Identify the current state','Explain the outcome','Offer a valid recovery action'],copy:'Use business-specific status labels. A status badge is not evidence that a workflow succeeded.',states:['Pending','In progress','Completed','Failed','Retry available']},
  agentic:{templates:[],match:/Livechat/i,steps:['State the task and scope','Inspect and lock the source','Confirm write authority','Execute within scope','Verify and report evidence'],copy:'Separate proposed actions from completed actions. Stop when authority or a required source is missing.',states:['Read only','Awaiting authority','Executing','Blocked','Verified result']}
};
function patternDoc(id,data) {
  const [,title,description]=patterns.find(x=>x[0]===id),g=patternGuides[id];
  const records=data.patterns.patterns.filter(x=>g.match.test(x.figmaName));
  const templates=data.templates.templates.filter(x=>g.templates.includes(x.canonicalName));
  return {title,description,group:'Patterns',badge:'Composition guidance',sections:[
    section('structure','Composition',note('Evidence boundary',data.templates.rule)+templates.map(t=>`<h3>${e(t.canonicalName)}</h3><ol class="steps">${t.typicalLayers.map(x=>`<li>${e(x)}</li>`).join('')}</ol>`).join('')+(!templates.length?`<ol class="steps">${g.steps.map(x=>`<li>${e(x)}</li>`).join('')}</ol>`:'')),
    section('workflow','Workflow guidance',`<p>${e(g.copy)}</p>`+list(g.steps)),
    section('states','Recommended state coverage',list(g.states)+`<p class="muted">This checklist is website guidance. Exact source states are shown below; unrecorded states are not claimed as audited.</p>`),
    section('sources','Related domain evidence',note('Registry policy',data.patterns.rule)+recordDetails(records,data.figma.figmaFileKey))
  ]};
}

function guideDoc(id,data) {
  const meta=routes.find(x=>x.id===id),base={title:meta.label,description:'',group:meta.group};
  const sourceLink=link(figmaLink(data.components.sourceFileKey),'Open Agency Portal Core DS');
  const definitions=[['Foundation','A visual decision such as color, typography, spacing or shape.'],['Core component','A reusable UI primitive with an owned Figma identity and API.'],['Domain pattern','A product-aware composition of Core assets.'],['Template','Composition guidance; not necessarily a published component.'],['Registry snapshot','A versioned audit record, not a live Figma synchronization.'],['Canonical naming','Normalized guidance; exact Figma API remains necessary for lookup.'],['Candidate','Requires identity/governance verification before reuse.']];
  if(id==='glossary')return {...base,description:'Terms used across the system.',sections:[section('terms','System vocabulary',`<dl class="glossary">${definitions.map(([a,b])=>`<dt>${e(a)}</dt><dd>${e(b)}</dd>`).join(''))]};
  if(id==='faqs') return {...base,description:'Source, implementation and verification questions.',sections:[section('answers','Questions and answers',[
    ['Which source defines Core DS?',`The Core registry points to file ${data.components.sourceFileKey}. Its audit date is ${data.components.auditDate}. Inspect the exact component node before reuse.`],
    ['Is this a live sync with Figma?','No. The published website displays a repository snapshot compiled during the build.'],
    ['Can I copy the examples into production?','Examples show native HTML behavior and mapped tokens. They are not a certified UI package; complete product wiring, visual checks and accessibility testing first.'],
    ['Why might the font look different?','The licensed DB Helvethaica X font file is not bundled. The site tries an installed local copy and otherwise uses fallback fonts.'],
    ['May I replace legacy Checkbox or Radio instances?','Not automatically. Follow the preferred-candidate matrix and obtain explicit migration scope.'],
    ['Does passing Agent tests prove the website matches Figma?','No. Agent policy tests do not render the website. Visual comparison, device and screen-reader evidence are separate.']
  ].map(([q,a])=>`<details class="faq"><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join(''))]};
  if(id==='icons') {const records=data.components.components.filter(x=>x.page==='Icon');return {...base,description:'Source-linked icon families, sizes and recorded variant counts.',sections:[section('catalog','Icon source catalog',note('Artwork availability','This repository contains icon identities but no exported SVG artwork. Inspect the source family; do not substitute unrelated glyphs or invent numeric icon meanings.')+recordsTable(records,data.components.sourceFileKey)),section('properties','Recorded properties',recordDetails(records,data.components.sourceFileKey))]};}
  if(id==='icon-usage')return {...base,description:'Select the correct source icon and preserve meaning.',sections:[section('rules','Selection and accessibility',list(['Use base-icon size and instance-swap properties recorded in the Core registry.','Pair unfamiliar icons with text.','Give icon-only actions an accessible name; decorative icons remain hidden to assistive technology.','Quick-menu numeric identities have unresolved semantics. Do not infer their meanings.'])),section('source','Source catalog',`<p><a href="#/icons">Browse icon families and exact nodes →</a></p>`)]};
  if(id==='axa-badge')return {...base,description:'Brand artwork is separate from component status badges.',badge:'Asset required',sections:[section('availability','Brand asset status',note('No approved AXA artwork in this repository','No logo/badge file or verified brand specification is bundled. Production usage is blocked until the approved asset, usage rights and placement rules are supplied. No replacement mark is generated.')),section('handoff','Required handoff',list(['Approved source asset and owner','Permitted variants and backgrounds','Clear-space and minimum-size rules','Usage rights for the deployment context'])+`<p>${sourceLink}</p>`)]};
  if(id==='resources')return {...base,description:'Direct links to the files used by this site.',sections:[section('sources','Authoritative records',`<div class="link-list">${Object.entries(data.sources).map(([k,path])=>link(repo(path),`${k} — ${path}`)).join('')}</div>`),section('figma','Design workspace',`<p>${sourceLink}</p>`)]};
  if(['agent','agent-workflow'].includes(id))return {...base,description:`Design Control Agent ${data.runtime.agentVersion}. Default permission: ${data.runtime.defaultWriteMode}.`,sections:[section('architecture','Operating model',table(['System','Responsibility'],Object.entries(data.runtime.architecture).map(([k,v])=>[e(k),e(v.replaceAll('_',' '))]))),section('sequence','Recorded runtime sequence',`<ol class="steps">${data.runtime.sequence.map(x=>`<li>${e(x.replaceAll('_',' '))}</li>`).join('')}</ol>`),section('guardrails','Invariants',list(data.runtime.invariants.map(x=>x.replaceAll('_',' '))))]};
  if(id==='skills')return {...base,description:'Contracts referenced by the Design Control Agent runtime.',sections:[section('contracts','Runtime contracts',table(['Contract','Repository source'],Object.entries(data.runtime).filter(([,v])=>typeof v==='string'&&/^(agent|skills)\/.*\.(json|md)$/.test(v)).map(([k,v])=>[e(k),link(repo(v),v)]))),section('authority','Permission boundary',note('Skills do not grant write authority','A loaded skill describes procedure. The current task must still authorize the exact write scope.'))]};
  if(id==='interaction-models')return {...base,description:'Predictable interaction when an agent proposes or performs work.',sections:[section('states','User-visible agent states',table(['State','User-facing behavior'],[['Inspecting','Read sources without mutation.'],['Awaiting authority','Explain the proposed change and material consequences.'],['Executing','Show scoped progress; do not claim verification yet.'],['Blocked','State the missing source, permission or evidence.'],['Verified','Report evidence and known limitations separately.']].map(r=>r.map(e)))),section('control','Control and recovery',list(['Keep proposed and executed actions distinct.','Do not retry uncertain writes before inspecting the resulting state.','Preserve a resumable checkpoint when blocked.']))]};
  if(id==='for-designers')return {...base,description:'Find the right Figma identity before composing a screen.',sections:[section('start','Design workflow',list(['Open the approved Core file and the intended product reference.','Find the component family and inspect the exact node.','Preserve recorded Figma property names during lookup.','Check candidate/legacy status and document unresolved source debt.'])+`<p>${sourceLink}</p>`),section('handoff','Before handoff',list(['Record component key, node, states and variables.','Include Desktop/Mobile source evidence where it exists.','Do not promote unverified examples to approved components.']))]};
  if(id==='for-developers')return {...base,description:'Use generated hooks and semantic examples with traceable sources.',sections:[section('setup','Implementation setup',code('<link rel="stylesheet" href="./tokens.css">\n<link rel="stylesheet" href="./styles.css">')+`<p><a href="./tokens.css" download>Download tokens</a> · <a href="#/components">Browse native HTML examples</a></p>`),section('contract','Implementation contract',list(['This website is static ES modules; it does not publish an npm component library.','Read exact Figma API and normalized guidance separately.','Wire product behavior explicitly and cover error/recovery states.','Run website interaction tests separately from Agent policy tests.']))]};
  return {...base,description:'Choose the source, select the correct system layer, then verify the result.',sections:[section('start','Start with your task',`<div class="category-grid">${card('for-designers','Design','Find canonical identities and source evidence.')}${card('for-developers','Develop','Use generated tokens and native HTML examples.')}</div>`),section('layers','Source hierarchy',list(['Core DS: foundations and cross-domain components.','Product source: task-specific content and behavior.','Domain pattern: reusable composition with recorded maturity.','Feature screen: local assembly, not a new global standard.'])),section('verification','Before calling work complete',`<p>Inspect source identity, compare the visual result and verify interaction independently. <a href="#/qa">Read the quality gates →</a></p>`)]};
}

function toolsDoc(id,data) {
  const base={title:routes.find(x=>x.id===id).label,group:'Tools',description:''};
  if(id==='figma')return {...base,description:'Exact source nodes and classifications from the repository snapshot.',sections:[section('core','Core component mapping',recordsTable(data.components.components,data.components.sourceFileKey)),section('product','Product page mapping',table(['Page','Classification','Use rule','Source'],data.figma.pages.map(p=>[e(p.figmaName),e(p.classification),e(p.implementation),link(figmaLink(data.figma.figmaFileKey,p.id),p.id)])))]};
  if(id==='registry')return {...base,description:'The data actually compiled into this website.',sections:[section('inventory','Published source inventory',table(['Record','Local data','GitHub'],Object.entries(data.sources).map(([k,path])=>[e(k),`<a href="./data/${e(path)}">View JSON</a>`,link(repo(path),'Read source')]))),section('coverage','Coverage',list([`${data.tokens.length} token records`,`${data.components.components.length} Core component records`,`${data.patterns.patterns.length} domain pattern records`,`${data.templates.templates.length} composition candidates`,`${data.qa.gates.length} quality gates (QA-01 is split into A and B)`])),section('maturity','Reuse decisions',note('Registry is not universal approval',data.components.rule)+list(data.preferred.unresolved))]};
  if(id==='qa')return {...base,description:'Actual quality-gate definitions, distinct from this website’s test results.',sections:[section('gates','Quality gates',table(['Gate','Name','Phase','Required evidence'],data.qa.gates.map(g=>[e(g.id),e(g.name),e(g.phase),e((g.requires||g.blockedWhen||[g.blocking?'Blocking gate':'Advisory gate']).join(' · '))]))),section('rule','Completion rule',`<p>${e(data.qa.completionRule)}</p>`),section('website','Website verification boundary',note('Separate evidence streams','Agent policy tests validate operating rules. Website tests cover routes, data rendering and interaction logic. Neither proves Figma pixel fidelity, actual device rendering or screen-reader conformance.'))]};
  if(id==='release-notes')return {...base,description:'Recorded website changes and their known limits.',sections:data.releases.map((r,i)=>section(`release-${i}`,`${r.date} · ${r.title}`,list(r.changes)+note('Known limits',r.limitations.join(' '))))};
  return {...base,description:'Inspect sources, browse records and understand verification requirements.',sections:[section('tools','System tools',`<div class="category-grid">${card('figma','Figma mapping','Exact component and product nodes.')}${card('registry','Registry','Published JSON sources and coverage.')}${card('qa','QA & governance','Actual gate names and evidence requirements.')}${card('release-notes','Release notes','Changes with explicit limits.')}</div>`)]};
}

export function pageData(id,data) {
  if(id==='not-found' || !routes.some(x=>x.id===id))return {title:'Page not found',description:'This address does not match a documentation page.',group:'Navigation',sections:[section('recovery','Find your destination','<p><a href="#/overview">Return to overview</a> or use Search to find a component, token or guide.</p>')]};
  if(id==='overview')return {title:'AH Design System',description:'Find source-backed components, design tokens and guidance for AdvisorHub.',group:'Get started',badge:'Registry-backed documentation',sections:[
    section('explore','Explore the system',`<div class="category-grid">${card('components','Components',`${data.components.components.length} source records across UI and icon families.`)}${card('hook-index','Styling hooks',`${data.tokens.length} generated hooks with source values.`)}${card('patterns','Patterns','Composition guidance and domain records.')}${card('for-designers','For designers','Inspect Figma identities and maturity.')}${card('for-developers','For developers','Use native HTML examples and generated CSS.')}${card('qa','Verification','Know what is tested and what still needs evidence.')}</div>`),
    section('snapshot','Current snapshot',list([`Core audit: ${data.components.auditDate}`,`Variables: ${data.tokens.length}`,`Quality gates: ${data.qa.gates.length}`,`Agent runtime: ${data.runtime.agentVersion}`])+note('Read the evidence boundary','Repository data is audited metadata. The examples have not been certified against live Figma screenshots. Licensed fonts and approved brand artwork are not bundled.'))
  ]};
  if(id==='components')return {title:'Components',description:'Find source records and native HTML examples. Maturity is shown on every detail page.',group:'Components',sections:[section('catalog','Component catalog',`<div class="inventory-toolbar"><label class="field">Find a component<input id="inventoryFilter" class="ah-input" type="search" placeholder="Try input, error or radio"></label><button type="button" id="clearFilters">Clear filters</button></div><div class="chip-row" aria-label="Component categories">${['All',...new Set(components.map(x=>x[2]))].map(x=>`<button type="button" class="chip" data-category="${e(x)}" aria-pressed="${x==='All'}">${e(x)}</button>`).join('')}</div><p id="catalogCount" role="status"></p><div class="component-catalog">${components.map(([key,name,category,description])=>{const records=componentRecords(data,name);return `<a class="component-card" data-category="${e(category)}" data-search="${e([name,category,description,JSON.stringify(records)].join(' '))}" href="#/component/${key}"><span class="catalog-symbol" aria-hidden="true">${e(name.slice(0,1))}</span><span><strong>${e(name)}</strong><small>${e(category)} · ${records.length?`${records.length} source records`:'Source missing / proposal'}</small><p>${e(description)}</p></span></a>`;}).join('')}</div><div id="catalogEmpty" class="empty" hidden><strong>No matching components</strong><p>Try a shorter query or clear the category and search.</p><button type="button" data-clear-filters>Clear filters</button></div>`)]};
  if(id.startsWith('component/'))return componentDoc(id.split('/')[1],data);
  if(id==='patterns')return {title:'Patterns',description:'Different workflows with related source evidence, not a new set of approved components.',group:'Patterns',sections:[section('catalog','Composition guides',`<div class="category-grid">${patterns.map(([key,name,description])=>card(`pattern/${key}`,name,description)).join('')}</div>`),section('domain','Domain pattern inventory',note('Registry rule',data.patterns.rule)+recordsTable(data.patterns.patterns,data.figma.figmaFileKey))]};
  if(id.startsWith('pattern/'))return patternDoc(id.split('/')[1],data);
  if(foundations.some(x=>x[0]===id))return foundationDoc(id,data);
  if(hooks.some(x=>x[0]===id))return stylingDoc(id,data);
  if(['tools','figma','qa','registry','release-notes'].includes(id))return toolsDoc(id,data);
  return guideDoc(id,data);
}

export function renderDocument(id,data) {
  const page=pageData(id,data),index=routes.findIndex(x=>x.id===id),next=routes[index+1];
  const toc=page.sections.map(s=>`<a href="#/${id}?section=${s.id}" data-section="${s.id}">${e(s.title)}</a>`).join('');
  const parent=page.group==='Components'?'components':page.group==='Patterns'?'patterns':page.group==='Tools'?'tools':'overview';
  return `<article class="docs-article"><nav class="page-toc" aria-label="On this page"><strong>On this page</strong>${toc}</nav><div class="article-main"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="#/overview">AH Design System</a><span aria-hidden="true">/</span><a href="#/${parent}">${e(page.group)}</a></nav><div class="eyebrow">${e(page.group)}</div><h1 tabindex="-1">${e(page.title)}</h1><p class="lede">${e(page.description)}</p>${page.badge?`<span class="page-badge">${e(page.badge)}</span>`:''}${id.startsWith('component/')?`<nav class="section-tabs" aria-label="Component sections">${toc}</nav>`:''}${page.sections.map(s=>`<section id="${s.id}" class="doc-section"><h2 tabindex="-1">${e(s.title)}</h2>${s.html}</section>`).join('')}<div class="page-feedback"><strong>Found a documentation issue?</strong>${link(`${rootRepo}/issues/new?title=${encodeURIComponent(`Documentation: ${page.title}`)}`,'Report on GitHub')}</div>${next?`<a class="next-page" href="#/${next.id}"><span>Next page</span><strong>${e(next.label)} →</strong></a>`:''}<footer class="doc-footer"><span>AH Design System · Core audit ${e(data.components.auditDate)}</span><a href="#/release-notes">Changes & known limits</a></footer></div></article>`;
}

export function createSearchIndex(data) {
  return routes.map(r=>{
    const p=pageData(r.id,data);
    const content=p.sections.map(s=>s.title+' '+textFromHtml(s.html)).join(' ');
    return {...r,description:p.description,text:`${r.label} ${r.group} ${p.description} ${content}`.toLowerCase()};
  });
}
